# generated by ChatGPT

import json
import boto3
from botocore.exceptions import ClientError

# Create a DynamoDB client
dynamodb = boto3.resource('dynamodb')
table = dynamodb.Table('DevGrowth')  # Make sure this matches your DynamoDB table name

def lambda_handler(event, context):
    try:
        body = json.loads(event['body'])
        user_id = body['userId']
        worked_on = body['workedOn']
        date = body['date']
        learned = body['learned']
        stuck_on = body['stuckOn']
        
        response = table.put_item(
            Item={
                'User ID': user_id,
                'Date': date,  # date as the sort key
                'Worked On': worked_on,
                'Learned': learned,
                'Stuck On': stuck_on
            }
        )

        # Return success response
        return {
            'statusCode': 200,
            'body': json.dumps({
                'message': 'Progress added successfully!',
                'item': response.get('Attributes', {})  # Return the created item, if applicable
            })
        }

    except ClientError as e:
        # Handle errors from DynamoDB
        print(f"Error adding item: {e.response['Error']['Message']}")
        return {
            'statusCode': 500,
            'body': json.dumps({
                'message': 'Failed to add progress',
                'error': e.response['Error']['Message']
            })
        }

    except Exception as e:
        # Handle other exceptions
        print(f"Unexpected error: {str(e)}")
        return {
            'statusCode': 500,
            'body': json.dumps({
                'message': 'Internal Server Error',
                'error': str(e)
            })
        }
